### PR TITLE
return operator

### PR DESCRIPTION
**Pull request by ledrui**
Put the bar "|" at the starting of the arrow instead of the end
from >| to |>

### CODE REVIEW

**Comment by GabrielRatener** [comment]
The tests that have the original syntax would need to be changed to reflect this. Also I like `val >|` and `|< val` cause it implies that a value is output then the function ends.

**Comment by GabrielRatener** [comment]
Why do you prefer `|>`?

**Comment by ledrui** [comment]
It look more like a normal arrow, which means something is going in that direction.  Since we cant use `>` then this  `|>` make sense

**Comment by ledrui** [comment]
And I'm adding insertion sort example to the example batch

**Comment by GabrielRatener** [comment]
But remember, we also have `val >>`, and `<< val` for yield, so there has to be two different symbol pairs. Think of yielding as `return + continue`, thus two arrows, and actual returning as `return + stop`, thus an arrow + a bar.

**Comment by ledrui** [comment]
Yeah! yield make sense since its `return  + continue` you have `> + >`.  For a simple return you just want `>`, since it's taken you use `|>`

**Comment by GabrielRatener** [comment]
How about removing the return syntax changes from this PR, I can then merge the example(s) you added. The return syntax requires a bit more thought, changing the syntax outright will mean having to change change the tests as well, so that should probably be a different PR.

**Comment by ledrui** [comment]
Sure

**Pull request merged**
